server:
    port: 8088
    context-path: /shensheng/

spring:
    freemarker:
        cache: false
        request-context-attribute: request
    datasource:
        url: jdbc:mysql://localhost:3306/test
        password: root
        username: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        prefix: /WEB-INF/page/
        suffix: .html

mybatis:
    mapper-locations: classpath:mapper/*.xml

logging:
    level:
        #root: debug
        com:
            shensheng: debug

security:
  user:
    name: admin
    password: admin
